### ISSUE TITLE
RM521F-GL Repo or Firmware?

### ISSUE THREAD

**Issue by snowzach** [iamromulan/RM520N-GL#2]
Any plans to create a repo for the RM521F-GL or possibly link the firmware `RM521FGLEAR05A02M4G_01.200.01.200.zip` Being trying to track it down.

**Comment by iamromulan** [comment]
I was going to soon 😁
Was hoping it would be out of the engineering sample phase first and we had a newer firmware.
https://mega.nz/file/7Q1DjSLJ#C7EicrIRcGRG2bsz92Q27VA_zfTE6IAfFTgiUsbanYk

**Comment by snowzach** [comment]
Thank you!!!

**Comment by snowzach** [comment]
Did you happen to figure out how to factory reset an RM521? 
I tried this
```
AT+QPRTPARA=1
AT+QPRTPARA=3
AT+CFUN=1,1
# AFTER REBOOT
AT+QPRTPARA=1
```
But it doesn't seem to do it.. I just want to make sure I didn't screw up any settings.

**Comment by iamromulan** [comment]
> Did you happen to figure out how to factory reset an RM521? 
> I tried this
> ```
> AT+QPRTPARA=1
> AT+QPRTPARA=3
> AT+CFUN=1,1
> # AFTER REBOOT
> AT+QPRTPARA=1
> ```
> But it doesn't seem to do it.. I just want to make sure I didn't screw up any settings.

When you set the modem to be used with an ethernet chipset directly like the MCU board the commands you use to put it in that mode are:
AT+QCFG="data_interface",1,0
AT+QETH="eth_driver","r8125",1
AT+QCFG="pcie/mode",1
AT+QCFG="usbnet",1

In usbnet 1 (ECM) AT+QMAPWAC always =1
any other mode you have to set this yourself.
MCU refers to this as switching between using cellular over Ethernet (1) and usb (0) but in reality its more of an auto connect setting of some sort. In (0) i believe its simply set to connect when the USB device wants to connect. Since in any mode but ECM most of the work for starting and keeping the connection is done by the device the modem is connected to, i believe this is a way to manually tell the system to ask for an IP from the carrier/connect.

My advise to make it work in a router again(not tested myself):
AT+QCFG="data_interface",0,0 (default)
AT+QETH="eth_driver","r8125",0 (or AT+QETH="eth_driver",0) (Need to disable the ethernet driver maybe?)
AT+QCFG="pcie/mode",0 (default)
AT+QMAPWAC=0 (default)
AT+QCFG="usbnet",0 (default usb mode)

(Default according to: https://mega.nz/file/zEEmCYTb#Y_YVlSEWNn9tz9dpHvY1rSZuDR_gEB6XEVIQ0nGrCJQ)

Oh and the command you want for a factory reset for these modems (check your IMEI before putting your sim back in!!):
Remove sim and reboot
AT+QPRTPARA=3
AT+CFUN=1,1
AT+QPRTPARA=1
AT+QCFG="ResetFactory" (the modem will reboot again here, this also wipes additions to the rootfs and /usrdata partitions, probably others too)

There are some AT commands you can't factory reset it seems though. Quectel and their AT commands have always been a head scratcher but I've done my best to try and understand.

**Comment by snowzach** [comment]
Awesome! Thanks... I saw that you had the QuWireless big boy antenna... I have the smaller https://www.quwireless.com/product/qupanel-5g-lte-mimo-4x4 one coming... Hopefully it increases my upload. I have 71+41,41 CA and download is great but upload is a little slow. Hoping that fixes me up.

**Comment by iamromulan** [comment]
Unfortunately that antenna is probably not the best bang and probably will be missing out on certain bands.
600-6000MHz antennas are what we want for these nice NR modules.
I've stuffed an MCUzone board inside both the larger directional

https://www.quwireless.com/product/qupanel-5glte-global-mimo-4x4-nf?variant=Nf

Also managed to stuff it in the smaller directional antenna too.

https://www.quwireless.com/product/quomni-5glte-global-mimo-4x4-nf?variant=Nf

I custom order them to have MHF4 connectors inside.

The small antenna I had them cap off the bottom hole and I drilled side holes for Power over  Ethernet, dual SIM, and USB C. All weather proof. 

![IMG20240214235149.jpg](https://github.com/iamromulan/RM520N-GL/assets/50184035/aa4d2010-fe3f-4a59-b72f-818486e901fa)

**Comment by snowzach** [comment]
That is a pretty sweet setup though... I'm gonna try to keep my waveshare board inside and just the antenna in the attic so I can still have USB on it. My board doesn't have a fan either so was worried about it getting hot outside or in the attic. I kinda wish I had gotten the fan one.
